const boy_names = [
    "shashwat", "abhaya",   "Dhonu",    "aalok",
    "abin",     "bijaya",   "Ganesh",   "abhidi",
    "aashish",   "gadit",   "Garvesh",  "Abhik",
    "roman",     "aakash",  "Hartaj",   "abhimand",
    "sushil",   "prashant", "Imay",     "abhimanyu",
    "nischal",  "prajwal",  "Indra",    "adhirath",
    "ajaya",    "ujjwal",   "indradu",  "abhirup",
    "suraj",    "laxmi",    "jaysha",   "achanda",
    "dipesh",   "Amir",     "prithivi",
    "madan",    "bibek",    "saudis",
    "hari",     "manish",   "sejun",
    "parixit",  "milan",    "shalva",
    "amrit",     "ram",     "salya",
    "ashwin",   "sajit",    "indragop",
    "kamal",    "sang",      "juddha",
    "krishna",  "abiral",   "sanani",
    "balkumar", "baburam",  "aadarsh",
    "ankit",    "Ballabh",  "Aakanksha",
    "arpit",    "Batsal",   "Aakar",
    "vishnu",   "Devnand",  "Aakarshan",
    "bishnu",   "Dhyansh",  "Alaap",
    
]
